### ISSUE TITLE
bevy_sprite should be should be behind a feature flag, not a hard dependency

### ISSUE THREAD

**Issue by rydb** [NiklasEi/bevy_common_assets#19]
I'm trying to optimize my cargo build times for my project, and a major slow down I've noticed for recompiles is bevy_sprite. I'm making a 3d project, and I'd like to be able to remove bevy_sprite, since I don't need it, but this crate makes it a hard dependency. 

A '2d' feature flag would let people who use this crate and bevy_asset_loader to remove bevy_sprite, and speed up re-compiles for 3d projects.

**Comment by NiklasEi** [comment]
Sorry, I don't see where `bevy_common_assets` makes `bevy_sprite` a hard dependency. A project with the following dependencies does not depend on `bevy_sprite`
```toml
[dependencies]
bevy = {version = "0.11", default-features = false }
bevy_asset_loader = "0.17.0"
bevy_common_assets = "0.7.0"
```
Could you please double-check your features and where the dependency comes from?
